--- 
      - 
        name: Install mysql dependencies
        yum: name=mariadb-server state=present
        
      - 
        name: Start mysql service
        service: name=mariadb state=started enabled=yes

      - 
        name: Create a database employee_db
        mysql_db: name={{ db_name }} state=present 

      - 
        name: Create a mysql user
        mysql_user:
          name: "{{ db_username }}"
          password: "{{ db_password }}"
          priv: '*.*:ALL'
          state: present