---

- name: Change root password
  remote_user: root
  hosts: target1
  gather_facts: no

  tasks:
    - 
      name: Create random password
      set_fact: 
        random_number: "{{ 100 | random | to_uuid | upper  }}"

    - 
      name: Print on the console
      debug: var=random_number

    - 
      name: Change root password
      shell: echo -e "{{ random_number }}" | passwd root --stdin

    -
      name: Send the password to gmail
      shell: echo -e "{{ random_number }}" | mail -v -s "root password has been changed" ansibletest17@gmail.com
